SELECT 
	CL.CODE AS "KODU",
	CL.DEFINITION_ AS "UNVAN",
	ROUND(ISNULL ((SELECT SUM(CASE CF.SIGN WHEN 0 THEN CF.AMOUNT ELSE CF.AMOUNT * - 1 END) FROM LG_001_01_CLFLINE CF WHERE CF.CANCELLED = 0 AND CF.CLIENTREF = CL.LOGICALREF), 0),2)AS [BAKİYE (TL)],
	CL.SPECODE AS "ÖZEL KOD",
	CL.SPECODE2 AS "ÖZEL KOD 2",
	CL.SPECODE3 "ÖZEL KOD 3",
	CL.SPECODE4 AS "ÖZEL KOD 4",
	CL.SPECODE5 AS "ÖZEL KOD 5",
	CL.EMAILADDR AS [MAIL 1]

--Logo'da kullandığınız şirket bilgilerine göre değiştirmeniz gerekmektedir.
FROM LG_001_CLCARD as CL with (nolock)
