SELECT 
	MALZEME.CODE AS [MALZEME KODU],
	MALZEME.NAME AS [MALZEME ADI],
	MALZEME.SPECODE AS [ÖZEL KOD 1],
	MALZEME.SPECODE2 AS [ÖZEL KOD 2],
	MALZEME.SPECODE3 AS [ÖZEL KOD 3],
	MALZEME.SPECODE4 AS [ÖZEL KOD 4],
	MALZEME.SPECODE5 AS [ÖZEL KOD 5],
	--SUM(ST.PURAMNT) AS [SATIN ALMA MİKTARI],
	--SUM(ST.PURCASH) AS [SATIN ALMA TUTARI],
	--SUM(ST.SALAMNT) AS [SATIŞ MİKTARI],
	--SUM(ST.SALCASH) AS [SATIŞ TUTARI],
	AMBAR.NAME AS [AMBAR ADI],
	
	SUM(ST.ONHAND) AS [MEVCUT]

FROM 
	LV_020_01_STINVTOT AS ST 
		LEFT JOIN LG_020_ITEMS MALZEME ON ST.STOCKREF = MALZEME.LOGICALREF 
		LEFT JOIN L_CAPIWHOUSE AS AMBAR ON ST.INVENNO = AMBAR.NR
    
-- ŞİRKET İLE AYNI FİRMA NUMARASI GİRİLECEK YOKSA NULL DEĞER DÖNDÜRÜR.
WHERE MALZEME.ACTIVE = 0 AND AMBAR.FIRMNR = 20

GROUP BY 
	MALZEME.CODE,
	MALZEME.NAME,
	ST.STOCKREF,
	AMBAR.NAME,
	MALZEME.SPECODE,
	MALZEME.SPECODE2,
	MALZEME.SPECODE3,
	MALZEME.SPECODE4,
	MALZEME.SPECODE5

ORDER BY 
	SUM(ST.ONHAND) DESC
